name: 'Kayley Stoner '
favicon: null
layout_spectrum: 0.5483287556562573
typography_spectrum: 0.41613444755785167
title: Georgia Family Law Attorney
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.8383864283096045
  lightness: 0.08616474806331098
  saturation: 0.535415239399299
  rhythmicContrast: 0.29274169565178454
purpose: []
